name = "mantiscan-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[vars]
APP_ENV = "production"
APP_URL = "https://mantiscan-api.diegosilang.workers.dev"
GITHUB_OWNER = "kebbbnnn"
GITHUB_REPO = "mantiscan"

[[d1_databases]]
binding = "DB"
database_name = "mantiscan-db"
database_id = "f7a1fb9a-b1a1-492e-a89c-23b865faefa6"
migrations_dir = "migrations"

[triggers]
crons = ["0 * * * *"]
